Fitter method to compute component-wise areas and their uncertainties
lbl-anp/becquerel pull request #303
Opened 2021-12-17 21:34 UTC by jvavrek

![image](https://user-images.githubusercontent.com/7683814/146610116-24eeb05d-cf5e-451c-b7ec-59cad67fa7f0.png)

```py
>>> fitter.calc_area_and_unc()
2002647.92714046+/-1415.3747870339978

>>> (fitter.y.sum(), np.sqrt(fitter.y.sum()))
(2002646, 1415.1487554317391)

>>> areas = [fitter.calc_area_and_unc(component=comp) for comp in fitter.model.components]
[99936.80253652389+/-656.5995003915539,
 99861.92313776605+/-645.2239560410361,
 1802849.20146617+/-1535.034662198673]

>>> sum([a.n for a in areas])
2002647.92714046
```

2021-12-18 00:56 UTC, jvavrek commented on becquerel/core/fitting.py
> +        g = np.atleast_2d(grad(values, xvals=xvals, model=model, names=names)).T
Something goes awry in these lines with `lmfit`. The `g` values differ between `lmfit` and `iminuit`, as does the order of the `names`/`values`. That probably throws a wrench into the `g * cov * g` multiplication, leading to the wrong uncertainty.

2022-01-05 20:14 UTC, jvavrek commented on becquerel/core/fitting.py
> +        g = np.atleast_2d(grad(values, xvals=xvals, model=model, names=names)).T
The issue is with `lmfit`:
```py
>>> list(fitter.result.best_values.keys())
['line_m',
 'line_b',
 'gauss1_amp',
 'gauss1_mu',
 'gauss1_sigma',
 'gauss0_amp',
 'gauss0_mu',
 'gauss0_sigma']

>>> list(fitter.params)
['gauss0_amp',
 'gauss0_mu',
 'gauss0_sigma',
 'gauss1_amp',
 'gauss1_mu',
 'gauss1_sigma',
 'line_m',
 'line_b',
 'gauss0_fwhm',
 'gauss1_fwhm']
```

We can fix this by using `fitter.param_names` (which works for both backends) and filtering out the `_fwhm` parameters:
```py
names = [name for name in self.param_names if self.params[name].vary]
values = [self.param_val(name) for name in names]
```

2022-01-05 23:58 UTC, markbandstra requested changes
Please add test(s) of the new method.

2022-01-06 00:20 UTC, jvavrek commented
> Please add test(s) of the new method.

Yeah, you got me there.

2022-01-06 03:30 UTC, jvavrek commented
@markbandstra I've added tests of the new method. Something strange is going on with `pytest-black` in the CI, but tests pass locally.

2022-01-06 03:43 UTC, jccurtis commented
> @markbandstra I've added tests of the new method. Something strange is going on with either `black` or `pytest-black` in the CI, but tests pass locally.

@jvavrek that is really weird. I triggered the jobs again. This appears to be something in `pytest-black` which was fixed in: https://github.com/shopkeep/pytest-black/issues/42

2022-01-06 03:46 UTC, jccurtis commented
@jvavrek can you try `pytest-black>=0.3.10`

2022-01-06 03:47 UTC, jccurtis commented
@jvavrek also try `pytest<7.0.0`

2022-01-06 04:21 UTC, jvavrek commented
> @jvavrek also try `pytest<7.0.0`

This worked 🚀

Why was the CI installing 7.x when conda and pypi both only have 6.2.5?

2022-01-06 04:58 UTC, merged

2022-01-06 05:36 UTC, jccurtis commented
> > @jvavrek also try `pytest<7.0.0`
> 
> This worked 🚀
> 
> Why was the CI installing 7.x when conda and pypi both only have 6.2.5?
> 
> Bizarrely, it looks like it was not installing 7.x: https://github.com/lbl-anp/becquerel/runs/4723159061?check_suite_focus=true#step:5:196

Well I'll be scratching my head on that one ... thanks for posting #307 ... I'm sure this will be resolved by the plugin developers eventually