Calibration raises warning when clipping to its range
lbl-anp/becquerel pull request #319
Opened 2022-02-16 07:14 UTC by markbandstra

Fixes #314. Now a warning is raised when a `Calibration` is clipped to its range. For example:

```python
import becquerel as bq
spec = bq.Spectrum.from_file("tests/samples/nai_detector.spe")
cal = bq.Calibration.from_linear([-10, 2.02], rng=[0, 1e5])
spec.apply_calibration(cal)
```

Yields:

```
SpeFile: Reading file tests/samples/nai_detector.spe
becquerel/becquerel/core/calibration.py:150: CalibrationWarning: Function values have been clipped because they are less than the lower range (0)
  warnings.warn(msg, CalibrationWarning)
Traceback (most recent call last):
  File "becquerel/becquerel/core/spectrum.py", line 1147, in apply_calibration
    self.bin_edges_kev = cal.ch2kev(self.bin_edges_raw)
AttributeError: 'Calibration' object has no attribute 'ch2kev'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "becquerel/becquerel/core/spectrum.py", line 1155, in apply_calibration
    self.bin_edges_kev = cal(self.bin_edges_raw)
  File "becquerel/becquerel/core/spectrum.py", line 535, in bin_edges_kev
    raise ValueError("Bin edge energies must be strictly increasing")
ValueError: Bin edge energies must be strictly increasing
```

2022-03-02 20:25 UTC, jccurtis commented on becquerel/core/calibration.py
>  DEFAULT_DOMAIN = (0, 1e5)
Add comment (note) before this about the required monotonicity in this range

2022-04-05 23:58 UTC, markbandstra commented
Also fixes #309. Ready for review.

2022-04-06 00:35 UTC, jvavrek requested changes

2022-04-06 00:35 UTC, jvavrek commented on becquerel/core/spectrum.py
> +    def from_file(cls, infilename, verbose=False, cal_kwargs={}):
Best to avoid mutable default params

2022-04-06 00:35 UTC, jvavrek commented on becquerel/parsers/cnf.py
> +def read(filename, verbose=False, cal_kwargs={}):
Mutable default params here too

2022-04-06 00:35 UTC, jvavrek commented on tests/calibration_test.py
> +        print(args[1])
```suggestion
```

2022-04-06 00:35 UTC, jvavrek commented on tests/calibration_test.py
>          cal1.inverse(2e6)
Can you expand this to show that we can update the range of `cal1` and make the error disappear?

2022-04-06 00:36 UTC, jvavrek commented
I still kind of think that the default domain and range should be unbounded, especially given that the `domain` is really only used for validation and default plot x values. But that's maybe for another time.

2022-04-14 19:36 UTC, markbandstra commented
Not sure how to clear the "changes requested" status of this PR given that I have resolved all of the issues flagged by @jvavrek ...

2022-04-14 20:00 UTC, jvavrek commented
> Not sure how to clear the "changes requested" status of this PR given that I have resolved all of the issues flagged by @jvavrek ...

I think I just had to hit Approve. Send it! 🚀

2022-04-14 20:56 UTC, merged